apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNREF6TWpJdwpNelU0TURCYUZ3MDBNREF6TWpJd016VTRNREJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDNnMvMVovUnFCQU0ycVZCZWNNWWZOeFJ5Qmw2cGQ4VEs2VmpwV2JhTVFFeVB2U3ppUApEUlVIUHFGV1ZnSkRNTGJpMEVmWjZFT3JvL3hQWVkvWXZydmpSb3YyVmtPNGJnZlZ1OW1CQ0VNdzQrZVIzeUlFCmJBcWJzeXNZM0dwbnl4UDdEeDBFbitMM0xYVHM3MmM5ODJ0SzJjNEwrR3ptRmw4NU1PRDc2UlJ6M2xQdC81bUgKWG53eUR0M3RiL0p1VE9pV2N2NFUzSG1jU0F2K1FncnRDd25KeE84S1FlcTNHcHorcWQwYnY1OHFPL09zenptVQp2NHhndmg3cXI2RjYwVnpXbTNwVHVqN25odXZ2ZVNhSEZqZFcwblpucVdoRUQyTndwWTlrSkN0Y0wwSmRUYUxOCkxZVzlnQko1YzlZSzhaT0dIQm1hL0QvOCtlUDJsK2VMZTVzTkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRNZWk2WTcvczEvZWF6UEI2SwpNNWt4cnlMTVBUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFEZ01ueXIyK1dOWHZ2MDNVb3hCTkFsd2NEOVFTCndvQkFkbHFtT2Q2eVFwbHBqeFAxd203UzZURjQyKy9CNkREUnVuK2grVXhCMnovaDhVWHpmUk54blZxaVAyeEsKQWRXOEtmNDdkaTVoWUNUb3hMN2JtUEZLMnpTVmFnN0duNTFZbUpqdVlNQUIyNEtBMDFFd1JlRFJWMjJsUk9idgo4V1AvOE1qeHE2N2k5RWJrSDY4RE1hRnArRHZHbGR1Yk1mRmtVdEYzdTVCU3FQREF3OTZtdDlGVVBXM2FOSE1lClZCNFFqamdTSlh2YWt4bkp0S0hFMVdSeE5FSUwwV05vbHppeU1ycTRDQkc1eTcyampxSVZsZWRsSUFNV3p5cU4KeVZsSzZPVEFOVkFDaGpWdU1ydjcxTXhmV0ROSWNVUGxzZDVIK1ExSllKZGpXSTdrd0lwcUY3cjgzUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://b1c6c4ae-0996-4385-a982-1c56ff7eeac1.k8s.ondigitalocean.com
  name: do-blr1-k8s-1-16-6-do-2-blr1-1584849439523
contexts:
- context:
    cluster: do-blr1-k8s-1-16-6-do-2-blr1-1584849439523
    user: do-blr1-k8s-1-16-6-do-2-blr1-1584849439523-admin
  name: do-blr1-k8s-1-16-6-do-2-blr1-1584849439523
current-context: do-blr1-k8s-1-16-6-do-2-blr1-1584849439523
kind: Config
preferences: {}
users:
- name: do-blr1-k8s-1-16-6-do-2-blr1-1584849439523-admin
  user:
    token: 0ca13704fb3664ec5a2cceaefd9d27183fd8347c5e249f37a1e21f66085e7236
