apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: wordpress

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress
  template:
    metadata:
      labels:
        name: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          imagePullPolicy: Always
          env:
          - name: WORDPRESS_DB_HOST
            value: db-svc:3306
          - name: WORDPRESS_DB_USER
            value: wordpress
          - name: WORDPRESS_DB_PASSWORD
            value: wordpress
          - name: WORDPRESS_DB_NAME
            value: wordpress
          ports:
            - containerPort: 80
              protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "http"
spec:
  rules:
    - host: wordpress.stackexpress.com
      http:
        paths:
        - backend:
            serviceName: wordpress-svc
            servicePort: 80